import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="text-3xl font-bold underline">
          This is header of the Page
        </div>
        {children}
        <div>This is Footer of the page </div>
      </body>
    </html>
  );
}
